version: '3.8'

services:
  rvc-api:
    build: .
    container_name: rvc-voice-api
    ports:
      - "8000:8000"
    environment:
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - PETER_VOICE_ID=${PETER_VOICE_ID}
      - STEWIE_VOICE_ID=${STEWIE_VOICE_ID}
      - PYTORCH_ENABLE_MPS_FALLBACK=1
    volumes:
      # Mount model assets (if you want to persist models outside container)
      - ./rvc/assets:/app/rvc/assets:ro
      # Mount temp directory for processing files
      - ./temp:/app/temp
      # Mount uploads directory if needed
      - ./uploads:/app/uploads
      # Mount public directory for video/image content
      - ../public:/app/public:ro
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (increased for model loading)
    deploy:
      resources:
        limits:
          memory: 8G  # Increased from 4G
        reservations:
          memory: 4G  # Increased from 2G

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: rvc-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # If using SSL certificates
    depends_on:
      - rvc-api
    restart: unless-stopped
    profiles:
      - with-nginx

networks:
  default:
    driver: bridge 